version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8001:8000"
      - "9229:9229"  # Debug port
    environment:
      - NODE_ENV=development
      - PORT=8000
    command: npm run dev:debug
    env_file:
      - .env
